### ISSUE TITLE
Welcome messages

### ISSUE THREAD

**Issue by Benjamindodgson** [Ours-Inc/benji-backend#157]
Add the following messages when channel is created. Send as system messages. 

1. "Hi [first name](user.objectid) 👋, we are so glad you are here!"
2. "Ours is a better way to communicate online and we want to show a few ways how we do that."
3. "First is to a set a time each day that you are most ready to READ/RESPOND to messages. We call this a "ritual". Every message anyone sends you will be displayed in your feed during this time. You can always access any message, but the idea here is to help you not be distracted through out your day."
4. "You may have noticed there isn't a send button! 😱 That's intentional. Simply swipe up on your message in order to send it. If you need to move the cursor, simply hold down on the spacebar. This gesture is to help reduce the number of accidental sends by adding a touch of intentionality 🤗. "
5. "All messages are set to READ manually. This ensures that you know when a message is actually read, not just scrolled too 🧐. Simply tap a message, you want to set, or pull up on the last message in the conversation."
6. "Hit us up in Feeback if you have issues or suggestions. Enjoy! 🥳 "

**Comment by gcolotti** [comment]
Send all these messages together, right?
