### ISSUE TITLE
Add User Local Preference for users

### ISSUE THREAD

**Issue by Benjamindodgson** [Ours-Inc/benji-backend#218]
When a connection is accepted, add a UserLocalPreference object to the userPreferences array on each user. 

UserLocalPreference 
- userId (User pointer Id)
- nickname (String)
- color (String)
- notes (String)

No public read/write. Just the user that owns the array.

**Comment by santiagosemhan** [comment]
- Add a column on User class named ** userPreferences**. 
- Given A <-> B connection, add an empty object (as described before) on **userPreferences** field for both A and B.


UserLocalPreference Structure:

```js
{
  "",
  "nickname": "",
  "color": "",
  "bio": ""
}
