### ISSUE TITLE
Channel Invite Post

### ISSUE THREAD

**Issue by Benjamindodgson** [Ours-Inc/benji-backend#239]
When a channel has a status = invited, add a post

author = channel author
body = "You have been invited to join (channel.friendlyName), by \(user.fullName)"
triggerDate = NULL
expirationDate = NULL
type = "channelInvite"
attributes = ["channelSid": channel.sid]
priority = 1
duration = 5
file = NULL

**Comment by santiagosemhan** [comment]
On which event **onChannelAdd** or **onChannelUpdate**?

**Comment by gcolotti** [comment]
> On which event **onChannelAdd** or **onChannelUpdate**?

Also, could you provide an example of how the status field?

**Comment by Benjamindodgson** [comment]
The channel object has a status property. Do this on onChannelUpdate.
